### ISSUE TITLE
More documentation please

### ISSUE THREAD

**Issue by ianbenlolo** [aspenforest/yfrake#4]
Thanks for the repo. 
Some lower level documentation would be appreciated. Maybe just an example of pulling in a securities' historical price data and plotting  it for example. It starts off with higher level async stuff and skips the basics.

Thanks

**Comment by aabmets** [comment]
@ianbenlolo 
I believe there to be a misunderstanding, correct me if I'm wrong.
YFrake does not require you to use asynchronous programming. This is also pointed out in the beginning of the documentation, where it's clarified that YFrake configures itself automatically depending if you are using it asynchronously or synchronously. If your program is not using async, YFrake is going to run in threaded mode, where the async stuff is happening behind the scenes in an internal separate thread, which you don't have to concern yourself about at all. 

The example which you are requesting is the following one:
```
from yfrake import client
from matplotlib import pyplot as plt

@client.session
def main():
    result = client.get(endpoint='historical_prices', symbol='msft')
    result.wait()
    close_prices: list = result.data['quotes']['close']  #  this is a list of close prices

    #  use regular plt code for plotting a list of values here.

if __name__ == '__main__':
    main()
```

This is the basic stuff which is all that a regular developer will ever need.
The example above can be easily derived from the multitude of examples available in the documentation.

YFrake returns JSON text from the Yahoo servers which the YFrake client parses into a Python dictionary object. Having the knowledge on how to use Python dictionaries is a standard requirement for working with YFrake. 

If you wish to know what is the structure of the returned dictionaries for each endpoint, please run the built-in YFrake server and make test requests from within your browser as explained in the documentation. The responses returned by the server have the same structure as the responses returned by the client in your code.

EDIT: 
The `result` object has three properties: `endpoint`, `error` and `data`, 
where `isinstance(result.data, dict | None) == True`, 
where `isinstance(result.error, dict | None) == True`
where `isinstance(result.endpoint, str) == True`

**Comment by aabmets** [comment]
@ianbenlolo 
Fixed code
