### ISSUE TITLE
Collecting Info

### ISSUE THREAD

**Issue by firmai** [aspenforest/yfrake#5]
Hi, great package, do you perhaps have some example code of how to grab **info** similar to https://github.com/ranaroussi/yfinance/ for multiple tickers to obtain information like company name, address, etc.? This would be useful as I from what I could see your package might be an order of magnitude faster.

**Comment by aabmets** [comment]
@firmai 
Sorry I haven't replied to you sooner, I was not monitoring this repo for issues.
Did you check the documentation: [Endpoints of YFrake](https://yfrake.readthedocs.io/en/latest/yfrake/endpoints.html) ?
I guarantee that you will find the endpoint that you're looking for if you play around in the Swagger API GUI. To access the GUI, run YFrake server on your localhost and navigate to the designated localhost port in your web browser. This is also described in the official docs of YFrake. I don't know from the top of my head what fields each endpoint returns.
